name: Aggiorna Lista Wiseplay

on:
  schedule:
    - cron: '0 * * * *' # Gira ogni ora
  workflow_dispatch: # Permette di avviarlo a mano

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installa dipendenze
        run: pip install cloudscraper beautifulsoup4

      - name: Esegui lo script
        run: python scraper.py

      - name: Salva i cambiamenti
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add playlist.json
          git commit -m "Aggiornamento lista automatica" || exit 0
          git push
