name: Aggiorna Lista Wiseplay

on:
  schedule:
    - cron: '0 * * * *' # Gira ogni ora
  workflow_dispatch: # Ti permette di avviarlo a mano dallo smartphone

permissions:
  contents: write # Forza i permessi di scrittura direttamente nel workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installa librerie
        run: pip install cloudscraper beautifulsoup4

      - name: Esegui lo script
        run: python scraper.py

      - name: Salva e carica il file JSON
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Aggiornamento automatico lista"
          file_pattern: 'playlist.json'
